eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: idThanhToan
            uri: lb://service-thanhtoan
            predicates:
              - Path=/thanhtoan
          - id: idChungThuc
            uri: lb://service-chungthuc
            predicates:
              - Path=/chungthuc
server:
  port: 9093
